# Generated by Django 4.1.1 on 2022-09-11 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_alter_speaker_biography'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='icon',
            field=models.ImageField(upload_to='static/icons/'),
        ),
    ]
