# Generated by Django 4.1.1 on 2022-09-11 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_alter_event_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='photo',
            field=models.ImageField(upload_to='static/speakers/photo/', verbose_name='Fotografía'),
        ),
    ]
